---
default_language_version:
  python: python3.8
default_stages: [ commit ]
fail_fast: false
minimum_pre_commit_version: 2.15.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            'flake8-comprehensions==3.5.0',
            'flake8-debugger==4.0.0',
        ]
        args: ["--config=.flake8"]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "./run-mypy.sh"
        language: python
        language_version: python3.8
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        # Print the number of files as a sanity-check
        verbose: true
